## sampleVar is the value that the app will pull from its environment to display on the webpage
sampleVar: default Helm value

## color is the color to use for the webpage background. Valid values are the Solarized colors: https://ethanschoonover.com/solarized/
color: red

replicaCount: 1

image:
  pullPolicy: IfNotPresent
  tag: "1.1.5"

## username and password will need to be replaced with a valid GitHub user and token with package:read permissions
imageCredentials:
  registry: ghcr.io
  username: someone
  password: token

podLabels: {}

service:
  type: ClusterIP
  port: 80
