name: CD
on:
  push:
    branches: [main]
    paths-ignore:
      - 'helm-dummyapp/**'

jobs:
  prep_env:
    uses: ./.github/workflows/prep-env.yml

  docker_cd:
    name: Build docker container
    runs-on: ubuntu-latest
    needs: [prep_env]
    outputs:
      image_tags: ${{ steps.meta.outputs.tag-names }}
    steps:
      - uses: actions/checkout@v7

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ needs.prep_env.outputs.image_name }}
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=sha

      - name: Login to GitHub container registry
        if: ${{ !env.ACT }}
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          driver-opts: network=host
          buildkitd-config-inline: |
            [registry."registry.localhost:5432"]
              http = true

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          build-args: |
            VERSION=${{ needs.prep_env.outputs.app_version }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  gitops_dev:
    name: Update dev GitOps environment
    runs-on: ubuntu-latest
    needs: [docker_cd]
    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v7
        with:
          repository: nrao/releng-aws-gitops
          token: "${{ secrets.GH_REPO_PAT }}"
          path: ./gitops

      - name: Update dev environment image tag
        run: |
          cd gitops/
          imageTag="$(echo "${{ needs.docker_cd.outputs.image_tags }}" | grep 'sha-')"
          chmod +x ./scripts/setEnvTag.sh
          ./scripts/setEnvTag.sh dummy-app aws-dev "$imageTag"
          git config user.email "releng-cd@nrao.edu"
          git config user.name "CD Bot"
          git add .
          git commit -m "chore(dev): Set dummy-app/aws-dev image tag to $imageTag"
          git push origin main

  argocd_dev:
    needs: [gitops_dev]
    uses: ./.github/workflows/argo-check.yml
    with:
      app_name: dummyapp-dev
    secrets:
      server: ${{ secrets.ARGOCD_SERVER }}
      username: ${{ secrets.ARGOCD_USERNAME }}
      password: ${{ secrets.ARGOCD_PASSWORD }}

  gitops_qa:
    name: Promote to QA
    runs-on: ubuntu-latest
    needs: [argocd_dev]
    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v7
        with:
          repository: nrao/releng-aws-gitops
          token: "${{ secrets.GH_REPO_PAT }}"
          path: ./gitops

      - name: Promote dev imageTag to QA
        run: |
          cd gitops/
          chmod +x ./scripts/promote.sh
          ./scripts/promote.sh dummy-app aws-dev aws-qa
          git config user.email "releng-cd@nrao.edu"
          git config user.name "CD Bot"
          git add .
          git commit -m "chore(qa): Promote dummy-app/aws-dev image to aws-qa"
          git push origin main

  argocd_qa:
    needs: [gitops_qa]
    uses: ./.github/workflows/argo-check.yml
    with:
      app_name: dummyapp-qa
    secrets:
      server: ${{ secrets.ARGOCD_SERVER }}
      username: ${{ secrets.ARGOCD_USERNAME }}
      password: ${{ secrets.ARGOCD_PASSWORD }}
