name: Cleanup GHCR
on:
  workflow_dispatch:
  schedule:
    - cron: "12 0 * * *"   # Daily a little after midnight (12:12 am)

jobs:
#   clean:
#     runs-on: ubuntu-latest
#     name: Delete untagged images older than 7d
#     steps:
#       - uses: snok/container-retention-policy@v3.1.0
#         with:
#           account: kdion-nrao
#           token: ${{ secrets.GHCR_PAT }}
#           tag-selection: untagged
#           image-names: "*"
#           cut-off: 7d
#           dry-run: true

  clean_untagged:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    name: Delete untagged images older than 7d
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          owner: nrao
          package: releng/dummy_app
          dry-run: true
          older-than: 7 days
