name: Cleanup PR Images
on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
        if: ${{ !env.ACT }}
        with:
          owner: nrao
          package: releng/dummy_app
          delete-tags: pr-${{ github.event.pull_request.number }}
